# Array Manipulations    
- Indexing & Slicing    
    - one-dimensional Indexing    
    - Multidimensional Indexing   
- Flatten  
  -  Flatten  
  - Ravel  
- Reshape  
- Join  
    i. Concatenate  
    ii. Stack  
- Horizontal Stack  
- Vertical Stack  
- Height Stack  
- Split  
- Broadcasting  

In [2]:
import numpy as np

In [6]:
# Adding, Removing and sorting elements
arr = np.array([3,10,2,3,4,5,6])
np.sort(arr)

array([ 2,  3,  3,  4,  5,  6, 10])

In [10]:
# concatenating
arr_1 = np.array([1,2,3,4,5])
arr_2 = np.array([6,7,8,9,10])
arr_3 = np.concatenate((arr_1, arr_2))
arr_3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])

# Concatenating along axis 0 (vertical concatenation)
result = np.concatenate((arr1, arr2), axis=0)
print(result)
 

[[1 2]
 [3 4]
 [5 6]]


In [17]:
# adding dimensions
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [25]:
# Adding new axis (Or expanding dimension)
# the current dimension is only one.
b = a[np.newaxis, :]
print(b)
print(b.shape)

[[1 2 3 4 5 6]]
(1, 6)


In [26]:
b = a[: , np.newaxis]
print(b)
print(b.shape)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)


In [29]:
# We can also use no.expand_dims
c = np.expand_dims(a , axis = 1)
print(c)
print(c.shape)


[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)


In [30]:
c = np.expand_dims(a , axis = 0)
print(c)
print(c.shape)

[[1 2 3 4 5 6]]
(1, 6)


In [33]:
# Indexing and slicing 
arr = np.array([1,2,3])
print(arr[1])
print(arr[:])
print(arr[-1])
print(arr[-2:])

2
[1 2 3]
3
[2 3]


In [36]:
# Selecting that fullfill certain condition
array = np.arange(20)
print(array[array%2 == 0])

[ 0  2  4  6  8 10 12 14 16 18]


In [38]:
# combining two conditions
print(array[ (array > 10) & (array < 25) ])

[11 12 13 14 15 16 17 18 19]


In [41]:
# np.non zero
arr = np.array([[1,2,3],
    [4,5,6],
    [7,8,9]        
])
b = np.nonzero(arr < 5)
b

# Explanation
# the value at [0][0] , [0][1] , [0][2] , [1][0]
# are less than 0

(array([0, 0, 0, 1]), array([0, 1, 2, 0]))

In [42]:
# we can create a list of the coordinates where the elements are less than 5 then we can do like this

list_of_coordinates= list(zip(b[0], b[1]))
print(list_of_coordinates)

[(0, 0), (0, 1), (0, 2), (1, 0)]


In [59]:
# Multidimensional Indexing

my_arr = np.array([ 
       [ [1,2,3,4,5],
        [6,7,8,9,10] ] ,
         [ [11,12,13,14,15],
        [16,17,18,19,20] ] 
])
print(my_arr.shape)
# lets get the no 20, we can see the array has 3 dimension
# we can access the no 20 as
sliced_arr = my_arr[1][1][4]
print(sliced_arr)

(2, 2, 5)
20


In [ ]:
# Flatten and Ravel

In [65]:
# Transposing and reshaping
data = np.array([ [1,2,3,4,5,6],[6,7,8,9,10,11]])
print(data.shape)
data

(2, 6)


array([[ 1,  2,  3,  4,  5,  6],
       [ 6,  7,  8,  9, 10, 11]])

In [66]:
print(data.T.shape)
data.T


(6, 2)


array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10],
       [ 6, 11]])

In [67]:
data.reshape(4,3)
# to reshape properlly new shape elements must be equal to previous shape elements



array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [68]:
# Flipping the array along row
np.flip(data)


array([[11, 10,  9,  8,  7,  6],
       [ 6,  5,  4,  3,  2,  1]])

In [69]:
np.flip(data , axis = 1)

array([[ 6,  5,  4,  3,  2,  1],
       [11, 10,  9,  8,  7,  6]])

In [71]:
# Flattening and ravel
original_data =  np.array([[1,2,3],[4,5,6]])
original_data.shape

(2, 3)

In [78]:
flatten_data = original_data.flatten() 
#flatten data isn't linked to original data
flatten_data

array([1, 2, 3, 4, 5, 6])

In [80]:
ravel_data = original_data.ravel() 
#ravel data is linked to original data
ravel_data

array([1, 2, 3, 4, 5, 6])

In [81]:
ravel_data[0] = 0

In [83]:
original_data
# we can see any changes in the ravel data changes the original data

array([[0, 2, 3],
       [4, 5, 6]])

In [4]:
# Stacking
# Horizontal Stack
arr1 = np.array([1,2,3])
arr2 = np.array([4, 5, 6])

# Horizontal stacking
result = np.hstack((arr1, arr2))
print(result)

[1 2 3 4 5 6]


In [6]:
# vertical stack
result = np.vstack((arr1 , arr2))
print(result)

[[1 2 3]
 [4 5 6]]


In [21]:
#height stack
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Height stacking
result = np.dstack((arr1, arr2))
print(result)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [13]:
# Splitting

arr_1 = np.array([
        [1,2,3,4,5,6],
        [7,8,9,10,11,12]
])
arr_2 = np.hsplit(arr_1,3) # Thiis splits the array into 3 equal shaped
print(arr_2[0])
print(arr_2[1])
print(arr_2[2])

[[1 2]
 [7 8]]
[[ 3  4]
 [ 9 10]]
[[ 5  6]
 [11 12]]


In [22]:
arr = np.arange(9)

# Splitting array into three equal parts
result = np.split(arr, 3)
print(result)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


In [18]:
# Broadcasting
arr_1 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(arr_1.shape)
arr_2 = arr_1 + 1; # Here scalar 1 is broadcasted to match the shape of arr_1
print(arr_2)

(3, 3)
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [19]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([10, 20, 30])

# Broadcasting arr2 to arr1 shape
result = arr1 + arr2
print(result)

[[11 22 33]
 [14 25 36]]
