# Basic Numpy practice

In [2]:
import numpy as np

In [3]:
my_list = [ 1 , 2 , 3 , 4 ]
my_list

[1, 2, 3, 4]

In [4]:
my_array = np.array([1,2,3,4,5])
my_array

array([1, 2, 3, 4, 5])

In [55]:
single_array = np.array([1,2,3]) 
multi_array = np.array([(1, 2, 3), (4, 5, 6)])
print("single dim array : ", single_array)
print("multi dim array  : \n", multi_array)

single dim array :  [1 2 3]
multi dim array  : 
 [[1 2 3]
 [4 5 6]]


In [10]:
import numpy as np 
import sys 
my_list = range(10000) 
print("Size of each element of list in bytes: ",sys.getsizeof(my_list))  
print("Size of the whole list in bytes: ",sys.getsizeof(my_list)*len(my_list))  
my_array = np.arange(10000) 
print("Size of each element of the Numpy array in bytes: ",my_array.itemsize) 
print("Size of the whole Numpy array in bytes: ",my_array.size*my_array.itemsize)

Size of each element of list in bytes:  48
Size of the whole list in bytes:  480000
Size of each element of the Numpy array in bytes:  8
Size of the whole Numpy array in bytes:  80000


In [14]:
import numpy as np
import time

# size of arrays and lists
size = 1000000

# declaring lists
my_list = range(0,size) 

# declaring arrays
my_array = np.arange(size) 
initialTime = time.time() #Set initial time

# Squaring each elements and storing in another list
squaredList = [a*a for a in my_list]

# calculating execution time
print("Time taken for squaring :",
	(time.time() - initialTime),
	"seconds")

# capturing time before the multiplication of Numpy arrays
initialTime = time.time()

# multiplying elements of both the Numpy arrays and stored in another Numpy array
resultantArray = np.square(my_array)

# calculating execution time
print("Time taken by NumPy for element wise squaring:",
	(time.time() - initialTime),
	"seconds")

Time taken for squaring : 0.10040688514709473 seconds
Time taken by NumPy for element wise squaring: 0.0011780261993408203 seconds


In [19]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Array Shape : ", arr.shape )
print("Array Size : ", arr.size )
print("Array dimension : ", arr.ndim )

Array Shape :  (3, 3)
Array Size :  9
Array dimension :  2


In [21]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
np.empty(5)

array([4.9e-324, 9.9e-324, 1.5e-323, 2.0e-323, 2.5e-323])

In [25]:
np.arange(1,100,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [27]:
np.linspace(10 , 20 , num = 20)

array([10.        , 10.52631579, 11.05263158, 11.57894737, 12.10526316,
       12.63157895, 13.15789474, 13.68421053, 14.21052632, 14.73684211,
       15.26315789, 15.78947368, 16.31578947, 16.84210526, 17.36842105,
       17.89473684, 18.42105263, 18.94736842, 19.47368421, 20.        ])

In [28]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
c = a - b 
c

array([20, 29, 38, 47])

In [37]:
a_1 = np.array([1,2,3,4,5,6,7])
b1 = a_1[:4]
b1

array([1, 2, 3, 4])

In [40]:
arr1 = np.ones(10)
arr2 = arr1
arr2[3] = 0
print(arr1)
print(arr2)

[1. 1. 1. 0. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 0. 1. 1. 1. 1. 1. 1.]


In [43]:
arr1 = np.ones(10)
arr2 = arr1.copy()
arr2[3] = 0
print(arr1)
print(arr2)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 0. 1. 1. 1. 1. 1. 1.]


In [46]:
arr = np.array([1, 2, 3, 4], dtype='i4')
arr.dtype

dtype('int32')

When creating an array the element must be convertible else it shows value error

In [49]:
arr = np.array(['a',2,3,4,5],dtype = np.uint8)

ValueError: invalid literal for int() with base 10: 'a'

In [51]:
array_int = np.array([1,2,3,4,5],dtype= np.float64)
print("Before type conversion : ",array_int.dtype)
new_array = array_int.astype(np.uint16)
print("After type conversion : ",new_array.dtype)


Before type conversion :  float64
After type conversion :  uint16


In [3]:
np.power(100, 8, dtype=np.int64)

10000000000000000

In [4]:
np.power(100, 8, dtype=np.int32)
#overflow error

1874919424